name: github_Actions_CI_basic
on: [push]
jobs:
  security_check_simple:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Node Version on Server
        run: node -v
      - name: Clone Repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.13.1"
      - name: Install dependencies
        run: |
          echo "Running installing packages..."
          yarn add
      - name: check for security
        run: |
          echo "Running security check 1..."
          sleep 5s;
          echo "Running security check 2..."
          sleep 5s;
